In [2]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager

from bs4 import BeautifulSoup

import time
import pandas as pd

In [3]:
import sys
import os

from tqdm.notebook import tqdm

# Add the script directory to the system path
script_path = os.path.abspath('/home/xev/research/nfld/scripts')  # Adjust the relative path as needed
sys.path.append(script_path)

In [4]:
file_path = '/home/xev/research/nfld/data/drug-list.xlsx'
data = pd.read_excel(file_path, engine='openpyxl', sheet_name='drug_list')
data

       Drug
0   DB00852
1   DB01136
2   DB05767
3   DB00363
4   DB05470
..      ...
92  DB07877
93  DB00040
94  DB08464
95  DB08465
96  DB00437

[97 rows x 1 columns]

In [5]:
from drugbank_scrape import scrape_drugbank

In [6]:
data['Name'] = None
data['Desc'] = None
data['US Approved'] = None
data

       Drug  Name  Desc US Approved
0   DB00852  None  None        None
1   DB01136  None  None        None
2   DB05767  None  None        None
3   DB00363  None  None        None
4   DB05470  None  None        None
..      ...   ...   ...         ...
92  DB07877  None  None        None
93  DB00040  None  None        None
94  DB08464  None  None        None
95  DB08465  None  None        None
96  DB00437  None  None        None

[97 rows x 4 columns]

In [7]:
for idx, row in data.iterrows():
    drug = row['Drug']
    print(f"Scraping {drug}...")
    name, desc, us_approved = scrape_drugbank(drug)
    data.at[idx, 'Name'] = name
    data.at[idx, 'Desc'] = desc
    data.at[idx, 'US Approved'] = us_approved

Scraping DB00852...
Scraping DB01136...
Scraping DB05767...
Scraping DB00363...
Scraping DB05470...
Scraping DB05250...
Scraping DB00163...
Scraping DB05017...
Scraping DB01050...
Scraping DB05412...
Scraping DB01708...
Scraping DB00328...
Scraping DB00818...
Scraping DB00795...
Scraping DB01065...
Scraping DB00170...
Scraping DB00171...
Scraping DB00244...
Scraping DB00277...
Scraping DB02709...
Scraping DB00396...
Scraping DB01197...
Scraping DB00233...
Scraping DB03461...
Scraping DB04395...
Scraping DB00783...
Scraping DB01406...
Scraping DB03147...
Scraping DB01229...
Scraping DB05507...
Scraping DB01393...
Scraping DB00257...
Scraping DB01254...
Scraping DB00530...
Scraping DB00882...
Scraping DB00499...
Scraping DB00338...
Scraping DB00583...
Scraping DB01248...
Scraping DB07724...
Scraping DB00857...
Scraping DB05187...
Scraping DB06292...
Scraping DB08915...
Scraping DB04971...
Scraping DB01008...
Scraping DB00694...
Scraping DB02342...
Scraping DB00613...
Scraping DB01087...
Scraping DB01834...
Scraping DB00367...
Scraping DB00993...
Scraping DB01915...
Scraping DB04132...
Scraping DB00917...
Scraping DB05161...
Scraping DB00357...
Scraping DB02458...
Scraping DB03003...
Scraping DB05408...
Scraping DB04866...
Scraping DB02901...
Scraping DB06151...
Scraping DB06777...
Scraping DB00132...
Scraping DB08804...
Scraping DB00615...
Scraping DB00845...
Scraping DB05007...
Scraping DB07556...
Scraping DB06710...
Scraping DB00339...
Scraping DB05301...
Scraping DB00858...
Scraping DB00984...
Scraping DB04839...
Scraping DB07557...
Scraping DB01033...
Scraping DB03516...
Scraping DB03310...
Scraping DB08907...
Scraping DB00052...
Scraping DB02007...
Scraping DB03758...
Scraping DB06831...
Scraping DB02424...
Scraping DB02754...
Scraping DB04493...
Scraping DB05134...
Scraping DB06070...
Scraping DB07594...
Scraping DB07877...
Scraping DB00040...
Scraping DB08464...
Scraping DB08465...
Scraping DB00437...

In [8]:
data

,Drug,Name,Desc,US Approved
0,DB00852,Pseudoephedrine,A medication used to treat congestion and a ru...,YES
1,DB01136,Carvedilol,A heart medication used to treat heart failure...,YES
2,DB05767,Andrographolide,No description available,Not approved
3,DB00363,Clozapine,A drug used to treat a severe form of a psychi...,YES
4,DB05470,VX-702,No description available,Not approved
...,...,...,...,...
92,DB07877,"8-(6-BROMO-BENZO[1,3]DIOXOL-5-YLSULFANYL)-9-(3...",No description available,Not approved
93,DB00040,Glucagon,A medication used to treat low blood sugar in ...,YES
94,DB08464,"METHYL 3-CHLORO-2-{3-[(2,5-DIHYDROXY-4-METHOXY...",No description available,Not approved
95,DB08465,"2-(3-AMINO-2,5,6-TRIMETHOXYPHENYL)ETHYL 5-CHLO...",No description available,Not approved
96,DB00437,Allopurinol,A medication used to treat a painful disease c...,YES

In [9]:
with pd.ExcelWriter(file_path, engine='openpyxl', mode='a') as writer:
    data.to_excel(writer, sheet_name='drug_list_complete', index=False)